version: '3.8'

services:
  safecleaning:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4323:4323"
    container_name: safecleaning-astro
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./dist:/app/dist:ro
